name: sahara
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  transparent_image: ^2.0.1
  responsive_builder: ^0.7.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/5.png
    - assets/6.png
    - assets/c1.jpg
    - assets/c2.jpeg
    - assets/c3.jpeg
    - assets/7.png
    - assets/8.jpeg
    - assets/10.png
    - assets/9.jpeg
    - assets/11.jpeg
    - assets/12.jpeg
    - assets/13.jpeg
    - assets/14.jpeg
    - assets/15.jpeg
    - assets/16.jpeg
    - assets/17.jpeg
    - assets/18.jpeg
    - assets/19.jpeg
    - assets/20.jpeg
    - assets/21.jpeg
    - assets/22.jpeg
    - assets/23.jpeg
    - assets/24.jpeg
    - assets/25.jpeg
    - assets/26.jpeg
    - assets/Sahara.png
    - assets/27.jpeg
    - assets/28.jpeg
    - assets/29.jpeg
    - assets/30.jpeg
    - assets/31.jpeg
    - assets/32.jpeg
    - assets/33.jpeg
    - assets/34.jpeg
    - assets/35.jpeg
    - assets/36.jpeg
    - assets/37.jpeg
    - assets/38.jpeg
    - assets/39.jpeg
    - assets/40.jpeg
    - assets/41.jpeg
    - assets/42.jpeg

